## TEMEL PYTHON NOTLARI
#### Ugur URESIN, Yapay Zeka Mühendisi | Veri Bilimci
#### Mail: uresin.ugur@gmail.com

### 09. Numpy Kütüphanesi

In [1]:
# KÜTÜPHANE EKLEME
import numpy as np

#### DİZİLER (ARRAYS)

**1 Boyutlu Diziler**

In [2]:
liste = [1,2,3,4,5]
liste

[1, 2, 3, 4, 5]

In [4]:
bir_boyutlu_dizi = np.array([1,2,3])
bir_boyutlu_dizi

array([1, 2, 3])

In [5]:
# ÖRNEK-1
ogrenci_no = np.array([101,102,103,104,105])

In [6]:
ogrenci_no.shape

(5,)

In [8]:
type(ogrenci_no)

numpy.ndarray

In [9]:
ogrenci_no.dtype

dtype('int64')

In [10]:
ogrenci_isim = np.array(["Ali","Beyza","Can","Duygu","Eren"])

In [12]:
ogrenci_isim

array(['Ali', 'Beyza', 'Can', 'Duygu', 'Eren'], dtype='<U5')

**2 Boyutlu Diziler** 

In [14]:
iki_boyutlu_dizi = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
iki_boyutlu_dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
iki_boyutlu_dizi.shape

(3, 3)

In [17]:
iki_boyutlu_dizi.size

9

In [21]:
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
x.shape

(25,)

In [23]:
x.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
y = x.reshape(5,5)

In [26]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Dizilerdeki Elemanları Seçme**

In [28]:
y[1]

array([5, 6, 7, 8, 9])

In [29]:
y[1,0]

5

In [30]:
y[1,2]

7

In [31]:
y[(y>9) & (y<21)] = 0

In [32]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 21, 22, 23, 24]])

**Dizilerde Küme İşlemleri**

In [34]:
x = np.array([1,2,3,4,5])
y = np.array([0,2,4,6,8])

In [35]:
np.intersect1d(x,y)

array([2, 4])

In [37]:
np.setdiff1d(x,y)

array([1, 3, 5])

In [38]:
np.union1d(x,y)

array([0, 1, 2, 3, 4, 5, 6, 8])

**Temel Numpy Metodları**

In [50]:
x = np.array([3, 2, 5, 1, 4, 5, 2])

In [54]:
np.sort(x)

array([1, 2, 2, 3, 4, 5, 5])

In [55]:
x

array([3, 2, 5, 1, 4, 5, 2])

In [56]:
np.unique(x)

array([1, 2, 3, 4, 5])

In [57]:
x

array([3, 2, 5, 1, 4, 5, 2])

In [59]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [63]:
np.full((2,4),"ali")

array([['ali', 'ali', 'ali', 'ali'],
       ['ali', 'ali', 'ali', 'ali']], dtype='<U3')

In [64]:
np.diag([1,3,5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [65]:
np.diag(["x","y","z"])

array([['x', '', ''],
       ['', 'y', ''],
       ['', '', 'z']], dtype='<U1')

In [66]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [67]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [68]:
np.arange("x","y")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [71]:
np.arange(5,70,8)

array([ 5, 13, 21, 29, 37, 45, 53, 61, 69])

In [78]:
np.linspace(0,100,5) #(başlangıç, son, değer adeti)

array([  0.,  25.,  50.,  75., 100.])

In [84]:
np.linspace(5,250) #değer adeti 'default' olarak 50'dir!

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105., 110.,
       115., 120., 125., 130., 135., 140., 145., 150., 155., 160., 165.,
       170., 175., 180., 185., 190., 195., 200., 205., 210., 215., 220.,
       225., 230., 235., 240., 245., 250.])

In [85]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

#### Random Modülü

In [91]:
x = np.random.randint(1, 11, size=(5,)) #np=kütüphane (numpy), random=modül, randint=fonksiyon/metod

In [92]:
x

array([ 3,  6, 10,  5,  5])

In [101]:
y = np.random.randint(1,21, size=(3,5)) #1 dahil (included), 21 hariç (excluded)

In [102]:
y

array([[19, 14,  1,  4,  1],
       [20, 18,  4, 18,  1],
       [ 1, 20, 13,  5, 15]])

In [103]:
z = np.random.random((3,3)) 

In [104]:
z

array([[0.64853848, 0.60501347, 0.73694832],
       [0.45061844, 0.14849793, 0.77809252],
       [0.27537812, 0.81969499, 0.0569919 ]])

https://en.wikipedia.org/wiki/Normal_distribution#/media/File:Normal_Distribution_PDF.svg

In [125]:
# NORMAL DAĞILIM
X = np.random.normal(0, 0.1, size=(10,10))
X

array([[-0.00073847, -0.00932228,  0.00556569,  0.09516733,  0.00181236,
        -0.05759854,  0.10726745,  0.08241178,  0.03090981,  0.09248776],
       [ 0.13606675,  0.16602061, -0.01010988, -0.04144953, -0.17481523,
         0.08676654, -0.14867833,  0.01873955,  0.043514  ,  0.06610091],
       [-0.06212991,  0.02797142,  0.00989979,  0.0606529 , -0.12334857,
        -0.07601605, -0.05493535, -0.0954798 , -0.00297851, -0.10145868],
       [ 0.02011675,  0.10134093,  0.31243745,  0.11992076, -0.03962529,
         0.1482589 ,  0.06667969,  0.13976695,  0.16350207, -0.023959  ],
       [-0.09042063,  0.05124868,  0.08440918, -0.04830482,  0.10609362,
        -0.08890345,  0.16663823,  0.0642469 ,  0.00268127, -0.13039268],
       [-0.07351352, -0.03561112, -0.18003902,  0.01274441,  0.0160075 ,
        -0.15673665, -0.00944629,  0.07279852, -0.03654939,  0.0143538 ],
       [-0.12981619,  0.07137633, -0.06903246, -0.02039615,  0.18308711,
         0.02144629, -0.11380448,  0.0037999 

In [126]:
X.mean()

0.007344698748988352

In [127]:
X = np.random.normal(0, 0.1, size=(1000,1000))
X

array([[-0.06677504, -0.0035861 ,  0.06802294, ..., -0.09598281,
        -0.07725166,  0.10509735],
       [-0.103439  ,  0.05919268, -0.05726318, ..., -0.1154462 ,
         0.01646313, -0.09022383],
       [-0.05039742,  0.05643421, -0.02227657, ...,  0.04332073,
         0.15299793,  0.02879588],
       ...,
       [-0.13832839,  0.19230977, -0.12524557, ..., -0.17428909,
         0.01761513, -0.04109523],
       [ 0.06235998,  0.1175108 ,  0.05970675, ..., -0.0043189 ,
         0.05848225,  0.05735606],
       [-0.13073013,  0.01573301, -0.01903643, ..., -0.00812319,
         0.00115293, -0.04957089]])

In [128]:
X.mean()

1.532460175214468e-05

**Eleman Silme**

In [152]:
# ÖRNEK-1
x = np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [153]:
np.delete(x, [0,3]) #1. ve 4. elemanı silme

array([20, 30, 50])

In [154]:
# ÖRNEK-2
x = np.linspace(1,21,20, endpoint=False)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [155]:
y = x.reshape(4,5)
y

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [156]:
np.delete(y, 0, axis=0)

array([[ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [157]:
y

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [158]:
np.delete(y, [0,3], axis=1)

array([[ 2.,  3.,  5.],
       [ 7.,  8., 10.],
       [12., 13., 15.],
       [17., 18., 20.]])

**Eleman Ekleme**

In [162]:
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [163]:
np.append(x, 6)

array([1., 2., 3., 4., 5., 6.])

In [164]:
np.append(x, [6,7])

array([1., 2., 3., 4., 5., 6., 7.])

In [165]:
y = np.linspace(1,8,8)
y

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [166]:
y = y.reshape(2,4)
y

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [168]:
np.append(y, [[9,10,11,12]], axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [171]:
np.append(y, [[10],[20]], axis=1)

array([[ 1.,  2.,  3.,  4., 10.],
       [ 5.,  6.,  7.,  8., 20.]])

#### Dizileri Dilimleme (Slicing)

In [177]:
x = np.linspace(1,24,24)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [181]:
x = x.reshape(4,6)
x

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.]])

In [190]:
x[0,2]

3.0

In [191]:
x[:,2]

array([ 3.,  9., 15., 21.])